### ISSUE TITLE
Can't Create new user

### ISSUE THREAD

**Issue by sulemankm** [Enalean/docker-tuleap-aio#15]
Hi I downloaded and installed the docker image.  Tuleap seems to be working fine, however, I'm unable to register a new user and login into the system as it is not sending new account verification email.

By the way is there a default admin login/password preconfigured into the system?

**Comment by tomcottier** [comment]
Hi, you can find the admin password by running: 

`docker exec -ti <container_name> cat /data/root/.tuleap_passwd`

Once you are logged as admin, you can validate new user accounts;

**Comment by zhanglongqi** [comment]
This one should be put in readme
