### ISSUE TITLE
docker volume is not docker command 

### ISSUE THREAD

**Issue by creulantadrien** [Enalean/docker-tuleap-aio#17]
Hello,

The provided docker command seems deprecated ... like "docker volume ..."
Is possible to update your documentation with the lastest docker version ?

Sorry if my english is bad 
Thank you

**Comment by LeSuisse** [comment]
Hello,

The provided command to create a data volume is not deprecated.

Please refer to the Docker documentation if you need more information: https://docs.docker.com/engine/reference/commandline/volume_create/.
