### ISSUE TITLE
Mail configuration

### ISSUE THREAD

**Issue by tuanha-viosoft** [Enalean/docker-tuleap-aio#19]
Hi,
I installed docker-tuleap-aio and run successfully.
But when I registered a new account, I can't get the validation email.

The web interface shows an error:
> The mail was not accepted for the delivery. Please contact the administrator. His email address is: codendi-admin@localhost.

Could you tell me how to set up the notification email?

Thanks and BRs

**Comment by tuanha-viosoft** [comment]
It works now.

**Comment by bevinhex** [comment]
how did you solved?

**Comment by ricardovigatti** [comment]
how did you solved? +1

**Comment by gBopHuk** [comment]
How did you solve this ?

**Comment by castaglio** [comment]
I know it could be too late but in case someone it's looking for an answer I followed the suggestion made in https://serverfault.com/a/661007/517391 and worked for me.
I'd recommend also to read the whole thread.
