### ISSUE TITLE
Impossible to use without https in docker image

### ISSUE THREAD

**Issue by nlescure** [Enalean/docker-tuleap-aio#20]
When you want to use the docker image, it is not possible to use it without https configured which is not a good thing to test easily. 

The VIRTUAL_HOST env variable is set to local.tuleap:8086 and used is the container, so I can access to : 
http://local.tuleap:8086/
Then, if I want to create an account, or to login, the url is : https://local.tuleap/account/login.php?return_to=%2F

I have no https so I can't do anything.

**Comment by vaceletm** [comment]
There is actually a workaround for that.

Once you have run the image once (hence `tuleap-data` volume is not empty) you can edit the tuleap config (/etc/tuleap/conf/local.inc) and customize `sys_domain_name` to be `local.tuleap:8086`, empty `sys_https_host`

**Comment by nlescure** [comment]
I try this and I tell you. Thanks for the tip.

**Comment by nlescure** [comment]
I don't see sys_domain_name : 
` grep domain /etc/tuleap/conf/local.inc | grep -v //
$sys_default_domain = 'local.tuleap:8086';
$sys_cookie_domain = 'local.tuleap:8086';
$sys_lists_domain = $sys_lists_host;
$sys_disable_subdomains = 1;
$sys_default_mail_domain = '';`

The values seem correct.

**Comment by nlescure** [comment]
Ok, it works only if I remove the value for sys_https_host as you said.

**Comment by vaceletm** [comment]
Ok I close the request then
