### ISSUE TITLE
Mail response

### ISSUE THREAD

**Issue by OnlineArts** [Enalean/docker-tuleap-aio#22]
Hey,

is there a possibility to receive mails and responses on artifacts? I'm using successfully Tuleap in a docker container on a "Plesk"dicated Debian-Server with remapped ports. I'm already able to send mails through SMTP 25/TCP. I'm running Dovecot on the host.

Kind regards

R. Martin

**Comment by vaceletm** [comment]
If you want to respond to artifact emails you should configure it as explained in the documentation: https://tuleap-documentation.readthedocs.io/en/latest/administration-guide/howto.html#activate-reply-to-artifacts-by-email

Does it anwser the question ?
