### ISSUE TITLE
Yet another MySQL error

### ISSUE THREAD

**Issue by c410-f3r** [Enalean/docker-tuleap-aio#25]
Fedora 25 with Docker 1.12.6 installed via `dnf install`.

http://pastebin.com/gGgw2ppx

```
# du tuleap-data/
4	tuleap-data/_data/root
8	tuleap-data/_data/lib/gitolite/.gitolite/hooks/gitolite-admin
12	tuleap-data/_data/lib/gitolite/.gitolite/hooks/common
24	tuleap-data/_data/lib/gitolite/.gitolite/hooks
8	tuleap-data/_data/lib/gitolite/.gitolite/logs
16	tuleap-data/_data/lib/gitolite/.gitolite/conf
8	tuleap-data/_data/lib/gitolite/.gitolite/keydir
60	tuleap-data/_data/lib/gitolite/.gitolite
96	tuleap-data/_data/lib/gitolite
14936	tuleap-data/_data/lib/mysql/tuleap
4	tuleap-data/_data/lib/mysql/test
996	tuleap-data/_data/lib/mysql/mysql
38500	tuleap-data/_data/lib/mysql
38600	tuleap-data/_data/lib
4	tuleap-data/_data/home
4	tuleap-data/_data/etc/ssh
4	tuleap-data/_data/etc/httpd
4	tuleap-data/_data/etc/logrotate.d
16	tuleap-data/_data/etc
38628	tuleap-data/_data
38632	tuleap-data/
```

**Comment by LeSuisse** [comment]
Confirmed on fresh install.

It was an issue introduced by this dev: https://tuleap.net/plugins/tracker/?aid=9970
It is fixed starting Tuleap 9.5.99.15 (https://gerrit.tuleap.net/#/c/7802/).

Next Tuleap stable release (Tuleap 9.6) will fix it.

**Comment by c410-f3r** [comment]
Nice! Thanks for the reply!

**Comment by VoltX** [comment]
After long search, (new in docker). The solution could be:

docker run -ti -e VIRTUAL_HOST=localhost -p 80:80 -p 443:443 -p 22:22 -v tuleap-data:/data enalean/tuleap-aio:9.5

This command force previous version and solve the problem until the next version.

Thanks @LeSuisse for the tip
