### ISSUE TITLE
how to startup Tuleap  in docker

### ISSUE THREAD

**Issue by carl19781107** [Enalean/docker-tuleap-aio#27]
dear all

The docker has already running:
root@ALMTuleap:~# docker ps
CONTAINER ID   IMAGE    COMMAND     CREATED      STATUS      PORTS        NAMES
6d655083e53e        enalean/tuleap-aio   "/root/app/run.sh"   4 hours ago         Up 4 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:222->22/tcp   reverent_shirley

Could you tell me how to startup Tuleap  in docker .Thanks.

Regards
Carl

**Comment by LeSuisse** [comment]
I'm not sure to understand the question. If you are able to access your instance you should take at the user and administration guide: https://tuleap-documentation.readthedocs.io/en/latest/

**Comment by vaceletm** [comment]
No anwsers since 20 days, I close the request
