### ISSUE TITLE
Too many redirects on login

### ISSUE THREAD

**Issue by JanoschDeurer** [Enalean/docker-tuleap-aio#29]
I set up a tuleap with docker behind a reverse proxy and get a *too many redirects* error on login. Here is my docker-compose.yml file:

```docker
tuleap:
  image: enalean/tuleap-aio
  environment:
    - VIRTUAL_HOST=tuleap.example.com
    - LETSENCRYPT_HOST=tuleap.example.com
    - LETSENCRYPT_EMAIL=bla.example.com
  volumes:
   - ./volumes/tuleap/data:/data
```

**Comment by JanoschDeurer** [comment]
Hey, thanks for the fast response. I included the following in my location part as given in the documentation:

```
        proxy_set_header X-Real-IP         $remote_addr;
        # Allow to know what is the original IP address (esp. for logging purpose as well as session management)
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        # Allow to know what is the original protocol (so Tuleap knows if things were in HTTPS)
        proxy_set_header X-Forwarded-Proto $scheme;
        # What is the name of the platform to the end users
        proxy_set_header Host              $host;
        # Write Destination header for Subversion COPY and MOVE operations
        set $fixed_destination $http_destination;
        if ( $http_destination ~* ^https(.*)$ ) {
            set $fixed_destination http$1;
        }
        proxy_set_header Destination $fixed_destination;
```

Sadly the error still exists. I did not configure the proxy_pass as this is automatically configured by the docker container of the reverse proxy. If you want to take a look, this is the domain:
[https://tuleap.infornautik.de/](https://tuleap.infornautik.de/)

**Comment by vaceletm** [comment]
what did you set as value of "sys_trusted_proxy" in tuleap local.inc ?

**Comment by JanoschDeurer** [comment]
Sorry for the late response and thanks again for the fast answer. I'm sorry something has come up, so that I lake the time to further investigate this. I will get back to you in a week or so.

**Comment by MarekSuchanek** [comment]
I had the same problem and setting `sys_trusted_proxy` with IP range used by Docker (172.17.0.1 and not 127.0.0.1) solved the issue...

**Comment by ThomasKoscheck** [comment]
All these tips are not working for me, still having the same error
