### ISSUE TITLE
postfix errors

### ISSUE THREAD

**Issue by rgstephens** [Enalean/docker-tuleap-aio#30]
I've downloaded the latest version and executed the following commands and I get 

```
mkdir /home/greg/tuleap-data
sudo docker run -d -p 8081:80 -p 8444:443 -p 8023:22 --name tuleap -e VIRTUAL_HOST=plex -v /home/greg/tuleap-data/ enalean/tuleap-aio
```

Here's the output from the [docker logs](https://gist.github.com/rgstephens/4e6edf2be73df891b6c481963fe3d3b4.js) command.

Here's a tail of the [/var/log/maillog](https://gist.github.com/rgstephens/a123e99eb5f642c110cdcd3a4eae641c.js).

**Comment by LeSuisse** [comment]
Hi,

Thanks for the report with the logs.

I've been able to reproduce, commit 5400ef5f90fd04 should fix the issue.

The Docker Hub is building the image, once it is done, could you pull the image again and check that the fix is also working as expected for you?

**Comment by rgstephens** [comment]
Thanks, that fixed it.
