### ISSUE TITLE
How to run in another port in docker?

### ISSUE THREAD

**Issue by robert2206** [Enalean/docker-tuleap-aio#31]
I'm trying with Vagrant mapping on port 8080 and running with VIRTUAL_HOST on localhost:8080 but only I get login, please help me

**Comment by davask** [comment]
@robert2206, Can you configure a proxy in front of your app to redirect 80, 443, 22 to whatever mapping you need ?

**Comment by vaceletm** [comment]
Hi @robert2206 you should replace `-p 80:80` by `-p 8080:80` on the run CLI
you'll probably have to edit `/etc/tuleap/conf/local.inc` to match `sys_domain_name` to your config
