### ISSUE TITLE
custom VIRTUAL_HOST

### ISSUE THREAD

**Issue by davask** [Enalean/docker-tuleap-aio#32]
Hi,

I m configuring tuleap behind a proxy with a different VIRTUAL_HOST value.

I got these failed status when installing tuleap for the first time : 

```bash

Starting httpd: Syntax error on line 90 of /etc/httpd/conf.d/tuleap-vhost.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty
                                                           [FAILED]
Starting crond:                                            [  OK  ]
Stopping nscd:                                             [FAILED]

```

in the same time my certificat are managed on the proxy side and not on the app side

is there any way to indicate tuleap to look at an external volume for the certificat ?

**Comment by vaceletm** [comment]
If Tuleap is not meant to be exposed public, the easiest way to go is to configure it to be behind reverse proxy: https://tuleap-documentation.readthedocs.io/en/latest/administration-guide/advanced-deployments.html#admin-howto-reverseproxy

That mean that no certificate should be used on Tuleap container.
