### ISSUE TITLE
Can't login tuleap

### ISSUE THREAD

**Issue by zysc8313** [Enalean/docker-tuleap-aio#34]
Hello,
this is the content of my docker-compose.yml

> version: '2'
> 
> services:
>   tuleap:
>     image: enalean/tuleap-aio
>     ports:
>       - "9001:80"
>       - "9002:443"
>       - "9003:22"
>     volumes:
>       - /srv/tuleap/data:/data
>     environment:
>       VIRTUAL_HOST: my-server-ip:9001

when I access the URL(http://my-server-ip:9001/), I can see the homepage. but when I input the user name and password and press the login button, it's automatically direct to https://my-server-ip:9001/account/login.php (for https the port should be 9002).

Is there any mistake in my docker-compose.yml?

**Comment by LeSuisse** [comment]
Hello,

Your Compose file is fine but at the moment the information given by VIRTUAL_HOST is used for both HTTP and HTTPS endpoints and the configuration file is set accordingly.
You can solve your issue by editing `/etc/tuleap/conf/local.inc` with the right parameters for your situation.

**Comment by zysc8313** [comment]
Thank you for your response!

$sys_default_domain
$sys_https_host
$sys_lists_host

**Comment by zysc8313** [comment]
Any solutions?

**Comment by LeSuisse** [comment]
Sorry, I miss the notifications about this.

In your case, the property sys_https_host should be edited.

**Comment by zysc8313** [comment]
I edited that variable, but still not work

**Comment by LeSuisse** [comment]
What value did you use for the parameter?

**Comment by vaceletm** [comment]
No anwsers since 1.5 months, I close the issue.
