### ISSUE TITLE
Code review with Tuleap Pull requests feature not visible

### ISSUE THREAD

**Issue by sharadvishe** [Enalean/docker-tuleap-aio#36]
Code review with Tuleap Pull requests feature is not available in docker image.
Button for Pull request is not visible. Kindly suggest if any plugin for git pull request.

**Comment by LeSuisse** [comment]
Hello,

The plugin Pull Request is in a dedicated package named tuleap-plugin-pullrequest which is not included in the image. If you install it, you will be able to enable the plugin from the site administration and access/create pull request in your Git repositories in Tuleap.

**Comment by LeSuisse** [comment]
Hi,

The pull request plugin is now embedded in the tuleap-aio image (see #47).
