### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by SladeRun14** [Enalean/docker-tuleap-aio#37]
## Reproduce (from source root directory):
docker build -t tuleap-test .
docker volume create --name tuleap-data
docker run -ti -e VIRTUAL_HOST=localhost -p 80:80 -p 443:443 -p 22:22 -v tuleap-data:/data tuleap-test

## Result:
standard_init_linux.go:187: exec user process caused "no such file or directory"

The repository image seems to be fine since the following works as expected, which would suggest that the problem lies with the code and not my system:
docker volume create --name tuleap-data
docker run -ti -e VIRTUAL_HOST=localhost -p 80:80 -p 443:443 -p 22:22 -v tuleap-data:/data enalean/tuleap-aio

### System:
Windows 10 Pro
Docker-CE
   Version 17.06.2-ce-win27 (13194)
   Channel: stable
   428bd6c

**Comment by SladeRun14** [comment]
## Fix: 
Run dos2unix on all script files.

Files cloned from the repo onto a DOS file are encoded with the infamous  "/bin/bash^M: bad interpreter:".  Running dos2unix encodes the files correctly and the Go exception disappears.

**Comment by LeSuisse** [comment]
Thank you for having kept us informed of the issue and how you have fixed it.

**Comment by SladeRun14** [comment]
De rien, mon cher Monsieur <sourire>
