### ISSUE TITLE
Too many redirect on login

### ISSUE THREAD

**Issue by stefanocog** [Enalean/docker-tuleap-aio#39]
I placed address ip of my haproxy into `$sys_trusted_proxies` but i have always "Too many redirects"

eg.
`$sys_trusted_proxies = '192.168.9.150';`

I see correctly into apache logs request from this IP (haproxy)

**Comment by LeSuisse** [comment]
Hello,

Does your proxy properly set the header X-Forwarded-Proto?

**Comment by stefanocog** [comment]
Ok Thanks, i've add `reqadd X-Forwarded-Proto:\ https`, now works, thanks
