### ISSUE TITLE
Project Home Page not found

### ISSUE THREAD

**Issue by jpboignard** [Enalean/docker-tuleap-aio#4]
I installed the docker image with "docker pull enalean/tuleap-aio" 
When I create a project and I call the Home Page
I get the following error on https://<hostname>/www/<projectname>/
"Sorry, page not found."

**Comment by vaceletm** [comment]
The HomePage service (storage of html files) is not supported in docker image (and will probably never be in it's current form).

You can disable/desactivate it at site admin level in "Predefined services"
