### ISSUE TITLE
Use a database in its own container

### ISSUE THREAD

**Issue by 5ika** [Enalean/docker-tuleap-aio#42]
Hi,
I want to create a Jelastic manifest to run your service on [Hidora](https://hidora.com) but your Docker image is not optimized for scalability because the database and the core app are in the same container.

How is it possible to separate it in a more "micro-services" approach with a db in a second container ?

**Comment by vaceletm** [comment]
Hi,

I don't see any issue for doing that. Can jelsatic rely on a docker-compose.yml ?
If yes, the best way would be to update the tuleap image so it tries to use a remote db when available and fallback to the local one when not available

**Comment by 5ika** [comment]
Jelastic use a markup similar to docker-composer (https://docs.cloudscripting.com/). It's easy to start a mysql server next to the main server but where could I modified the configuration in order to use a remote db ?

**Comment by tcottier-enalean** [comment]
In your data volume have a look at etc/tuleap/conf/database.inc

**Comment by vaceletm** [comment]
I created a request on tuleap.net to follow this request https://tuleap.net/plugins/tracker/?aid=10814

**Comment by LeSuisse** [comment]
[request#10814](https://tuleap.net/plugins/tracker/?aid=10814) has been closed and #48 merged.

You will find a Docker Compose file usable with the latest Docker image, from I saw of the Jelastic markup it should easy enough to do the conversion. Can you check if it's ok?

**Comment by 5ika** [comment]
Hi guys,
I've just finished a first version : https://github.com/HidoraSwiss/manifest-tuleap
Everything works find with the external database. Thank you !
I could close this issue now :-)

**Comment by vaceletm** [comment]
Awesome !
Can we point toward your code as "Jelastic manifest" in our next release note ?

**Comment by 5ika** [comment]
Yes, with pleasure 👍  Thank you
