### ISSUE TITLE
gitolite password

### ISSUE THREAD

**Issue by klyngen** [Enalean/docker-tuleap-aio#43]
I am currently writing a report comparing different tools for agile development. The install was easy enough, however when I tried to use the git features I had problems. Gitolite asks for a password, and after googling for an hour I see that this has something to do with the ssh keys.

**Comment by nterray** [comment]
> I see that this has something to do with the ssh keys.

Yes you are right.

Did you manage to solve your issue? What is your question?

**Comment by klyngen** [comment]
No, I have not managed to solve the issue yet. And I do not have the knowledge to debug the issue. My question is really: "How to make it work".

**Comment by nterray** [comment]
The user documentation[1] says:

> Git access (for both read and write operations) requires a valid SSH key to be configured in user account preference.

Therefore you need to generate a ssh key and paste the public part in your account page.

Does it answer your question?

[1] http://tuleap-documentation.readthedocs.io/en/latest/user-guide/git.html#version-control-with-git

**Comment by klyngen** [comment]
Yes this solved everything.... I had a major brain lag. Now I feel really stupid....
