### ISSUE TITLE
Error when restarting Tuleap in docker

### ISSUE THREAD

**Issue by martiou** [Enalean/docker-tuleap-aio#44]
The container docker Tuleap starts well the first time.
At the restart of the container, Tuleap no longer works: issues # 35, # 33 ...

After several tests, I fixed the problem as follows:

1)  for Mysql: modification of the my.cnf file located in /data/etc :
```
#datadir=/var/lib/mysql
datadir=/data/lib/mysql
socket=/var/lib/mysql/mysql.sock
#socket=/data/lib/mysql/mysql.sock
```
Indeed the paths point by default in /var/lib/mysql at the restart of the container: the sources tuleap-bin.000 ***, directory tuleap, ... are not present and the server mysql can not start.
The default mysql.sock in persistent data /data/lib/mysql/mysql.sock does not seem to work for docker, or replacing the socket in /var/lib/mysql/mysql.sock

---------------------------------------------------------------------------------------------
2) Once the mysql problem is fixed, it's apache's turn.
Similar concern, the system expects confs at /etc/httpd/conf and /etc/httpd/conf.d, by default these reboot directories no longer exist.

The "wrongdoers": boot-fixpath.sh
```
[-d /etc/httpd/conf] && rm -rf /etc/httpd/conf
[-d /etc/httpd/conf.d] && rm -rf /etc/httpd/conf.d
```

with errors on symbolic links already created
```
cd /etc/pki/tls/private
ln -s /data/etc/pki/tls/private/localhost.key localhost.key
...
```
=> it would have been nice to test the existence of these symbolic links to avoid errors

The instructions following these errors are therefore not:
```
cd /etc/httpd
ln -s /data/etc/httpd/conf conf
ln -s /data/etc/httpd/conf.d conf.d
```

By moving the instruction before the error, apache run : the tuleap container restarts and everything works.

Based on my analysis, if you could incorporate permanent fixes into your future shipments on the docker hub, this would allow everyone to test and use Tuleap stably with docker.

Thank you Best regards

**Comment by tcottier-enalean** [comment]
Hi, thanks for the report. Could you submit a PR to have a better view of what you did?

**Comment by vaceletm** [comment]
Will be addressed when https://tuleap.net/plugins/tracker/?aid=10814&group_id=101 will be merged.

Thanks for the report

**Comment by LeSuisse** [comment]
[request#10803](https://tuleap.net/plugins/tracker/?aid=10803) has been closed with a fix for this issue. The Docker image has been updated (https://hub.docker.com/r/enalean/tuleap-aio/builds/bzpttrkrfelmlkzmvucesj/).
