### ISSUE TITLE
Use a external SSL/TLS reverse proxy

### ISSUE THREAD

**Issue by 5ika** [Enalean/docker-tuleap-aio#49]
Hi guys,
I'm still trying to adapt the Docker image for Jelastic.
Everything works fine and it's possible to quickly launch a Tuleap instance.
Now, I'm trying to use a valid SSL/TLS certificate automatically provided by Jelastic instead of the self-signed generated by Tuleap during the installation.

I've tried to modified the NGINX configuration in order to use the http port only but it seems there is a internal redirection to 443 in Tuleap. When I tried to access to the web page, I obtain a redirection loop.

How can I modify the configuration to use the Jelastic (Hidora) certificate with Tuleap ?

This is the configuration I tried in `/etc/nginx/conf.d/tuleap.conf`:
```
upstream tuleap {
    server 127.0.0.1:8080;
}

server {
    listen       80;
    server_name  tuleap-test.hidora.com;

    location /.well-known/ {
      root /opt/letsencrypt;
    }

    #location / {
    #  return 301 https://$server_name:443$request_uri;
    #}
  
  	include conf.d/tuleap.d/*.conf;
}
``` 

And this is what I'm trying to have : 

![tuleap reverse proxy for ssl_tls](https://user-images.githubusercontent.com/7430173/33369713-bf5e9d04-d4f5-11e7-9024-8ef7ac85b406.png)

**Comment by LeSuisse** [comment]
Hello,

Did you check the documentation about deployment behind a reverse proxy: https://tuleap-documentation.readthedocs.io/en/latest/administration-guide/advanced-deployments.html#configure-tuleap ?
I'm guessing the `local.inc` is not setup correctly or Tuleap code does not get the expected headers.

**Comment by 5ika** [comment]
It works ! Thank you for your link.
Tuleap is now fully configured for Jelastic platforms (https://github.com/HidoraSwiss/manifest-tuleap)
