### ISSUE TITLE
SSL Not secure, Http Only not working.

### ISSUE THREAD

**Issue by feuerball11** [Enalean/docker-tuleap-aio#50]
Hi, i want to have tuleap Docker on an Plesk server. I run into following problems, i'm unable to solve: 

1. If i use https, chrome response is, that the page is "insecure". Through that i have anoying warnings, and often pages that load incorrectly. 
2. If i try to switch to http instead, i get redirected back to https. I tried to set sys_https_host to nothing. but i still get redirected to https. 

I'm new to ssl and that kind of stuff, so anyone can give me a hint into the right direction, to solve this? i realy want to try tuleap, but with this issues its impossible.

**Comment by tcottier-enalean** [comment]
You need to generate a well signed cerfiticate to avoid the insecure warning of your browser.

Have a look at: https://certbot.eff.org/ (there is a plesk section).

**Comment by feuerball11** [comment]
i'm a bit confused about that. my plesk has already an ssl certificate, so i thought i need to do this inside the docker image. but i cant log in through ssh. So how do i do that?

**Comment by tcottier-enalean** [comment]
Does your plesk works as a reverseproxy or does the docker image is directly exposes to the Internet?

**Comment by feuerball11** [comment]
The docker image is directly exposed on port 4543->443

**Comment by feuerball11** [comment]
Ok Never mind. After long Fiddling i found the solution. To all who might have the same problem: 
the ssl COnfiguration is done in /etc/nginx/conf.d/tuleap.conf
