### ISSUE TITLE
invalid --dbdriver upon restarting docker

### ISSUE THREAD

**Issue by stanisworking** [Enalean/docker-tuleap-aio#53]
Hi,

I am able to run docker with the following command:
```
$> docker volume create --name tuleap-data
$> docker run --name tuleap -d -ti -e VIRTUAL_HOST=localhost -p 80:80 -p 443:443 -p 22:22 -v tuleap-data:/data enalean/tuleap-aio
```

When I stop and start the container, I encountered the following error:
```
+ pushd .
/ /
++ dirname /usr/share/tuleap/tools/docker/tuleap-aio/run.sh
+ curdir=/usr/share/tuleap/tools/docker/tuleap-aio
+ '[' -d /usr/share/tuleap/tools/docker/tuleap-aio ']'
+ cd /usr/share/tuleap/tools/docker/tuleap-aio
+ source mysql-utils.sh
++ set -e
++ set +x
Update data ownership to current image...chown: cannot access `/data/etc/httpd/conf.d/codendi_svnroot.conf': No such file or directory
chown: cannot access `/data/etc/httpd/conf.d/codendi_svnroot.conf.old': No such file or directory
chown: cannot access `/data/lib/tuleap/boomerang': No such file or directory
chown: cannot access `/data/lib/tuleap/forumml': No such file or directory
chown: cannot access `/data/lib/tuleap/trackerv3': No such file or directory
chown: cannot access `/data/lib/tuleap/secure_ftp/*': No such file or directory
chown: cannot access `/data/lib/tuleap/svnroot/*': No such file or directory
chown: cannot access `/data/home/groups/*': No such file or directory
chown: cannot access `/data/lib/tuleap/ftp/pub/*': No such file or directory
DONE !
Start mysql
180227 01:29:47 mysqld_safe Logging to '/var/lib/mysql/a9e548afdaa9.err'.
180227 01:29:47 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
PHP Notice:  Undefined index: dbdriver in /usr/share/forgeupgrade/forgeupgrade.php on line 115
PHP Notice:  Undefined index: dbdriver in /usr/share/forgeupgrade/forgeupgrade.php on line 120
Error: invalid --dbdriver
PHP Fatal error:  Class '' not found in /usr/share/forgeupgrade/forgeupgrade.php on line 130
```

Any guide to resolve this problem?
Thank you for your help.

**Comment by LeSuisse** [comment]
Hello,

Glad to see you have been able to solve your issue #52.

You encounter a bug that has been present between Tuleap 9.17.99.163 and Tuleap 9.17.99.191 (see [request #11187](https://tuleap.net/plugins/tracker/?aid=11187)), sorry about that.

If do not have yet started to play with your Tuleap instance, the easiest way out is probably to trash the data volume and pull the new image before starting over:
```
$ docker volume rm tuleap-data
$ docker pull enalean/tuleap-aio
$ docker volume create --name tuleap-data
$ docker run --name tuleap -d -ti -e VIRTUAL_HOST=localhost -p 80:80 -p 443:443 -p 22:22 -v tuleap-data:/data enalean/tuleap-aio
```

Else you can also redeploy correctly the configuration file inside the container: `install --group=codendiadm --owner=codendiadm --mode=0644 /usr/share/tuleap/src/etc/forgeupgrade-config.ini.dist /etc/tuleap/forgeupgrade/config.ini`

**Comment by stanisworking** [comment]
That seems to work. Thanks!
Will update if there is a new error.

**Comment by LeSuisse** [comment]
There was a bug for a few Tuleap versions where a configuration file was not properly deployed leading to the issue you observed.

Dropping the data volume and pulling the latest version (which does not have the bug anymore) solve that since the configuration file is properly deployed.

Since the original is solved (forgeupgrade crashing during the start), I'm closing this.
