### ISSUE TITLE
Tuleap project link show 404

### ISSUE THREAD

**Issue by sherinwip** [Enalean/docker-tuleap-aio#56]
When i pulled the latest docker image for Tuleap and started it everything works except for project links .when i click on projects it gives me error as 404 Not Found.Let me know what all information would be needed to debug this issue further

**Comment by LeSuisse** [comment]
Hi,

I have not been able to reproduce the issue you describe.

Can you provide the URL of a page where you have the issue?

**Comment by toben** [comment]
I am not using docker but I have the same issue since the last update. I don't know how to solve this. I am using Apache for tuleap 10.3.99.85-1.el6

**Comment by LeSuisse** [comment]
No response from OP since more than 2 months, closing.

@toben: I'm not sure if your issue is similar. You could try to run the following command inside the container then restart it: `/usr/share/tuleap/tools/utils/php56/run.php`. If that does not work please open a dedicated issue.
