### ISSUE TITLE
How to install on "old" mac with docker?

### ISSUE THREAD

**Issue by jyterrien** [Enalean/docker-tuleap-aio#58]
On MacOS, Docker installs natively with Docker.app. But on older machines Docker.app does not work. so you have to use Docker tools. (Docker.app depend on Hypervisor.framework)
In this case the Docker containers are hosted on a virtual machine running in the background.

the provided procedure appears to be written for a linux machine that hosts the Docker container itself.

I did not understand how to transpose it in the case of a VM.

I tried to install on a Windows7 PC that is in the same situation: windows + VM.

**Comment by tcottier-enalean** [comment]
Hi, 

As your question is purely docker related, I suggest you to ask it on the docker community channels, you will probably have much better answers there.

**Comment by vaceletm** [comment]
As Thomas said, it's more pure docker question and you will probably find better answer in their forum.

However there is not really anything "linux" related in this image so there is no reason it doesn't work even in a VM environment.

Typically here, the issue you have is that you try to bind port 22 on the VM and it's likely to be already in use. I would suggest to just remove it (-p 22:22) or to move it on another port
