### ISSUE TITLE
Changing the web context

### ISSUE THREAD

**Issue by Salimlou** [Enalean/docker-tuleap-aio#6]
Hi,

First of all thank you for this tool!! amazing!!

Is it possible to change the root url with an env variable? instead of just localhost, I can access the tool with localhost/tuleap for instance?

Thank you!

**Comment by vaceletm** [comment]
Hi,

No you can't.
You can set a different port (for instance localhost:8888) and/or to use a reverse proxy to present a different domain name

**Comment by Salimlou** [comment]
Okay! thank you!
