### ISSUE TITLE
Error running Tuleap Image on Docker on RHEL 7.5

### ISSUE THREAD

**Issue by fagnerffcs** [Enalean/docker-tuleap-aio#62]
After I run: docker run -ti -e VIRTUAL_HOST=localhost -p 80:80 -p 443:443 -p 22:22 -v tuleap-data:/data enalean/tuleap-aio

Console shows me this error message:

mv: inter-device move failed: `/etc/httpd/conf' to `/data/etc/httpd/conf'; unable to remove target: Directory not empty

**Comment by fagnerffcs** [comment]
Problem persists even on Docker CE 18.09.06... Any news about this?

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
