### ISSUE TITLE
Tags are not pushed since 10.0

### ISSUE THREAD

**Issue by nullterminated** [Enalean/docker-tuleap-aio#66]
[Latest release](https://www.tuleap.org/resources/release-notes) version is 10.9, but latest tag is 10.0 on [github](https://github.com/Enalean/docker-tuleap-aio/tags) and [docker hub](https://hub.docker.com/r/enalean/tuleap-aio/tags).

**Comment by vaceletm** [comment]
Tags are no longer pushed because :latest is since in rolling release. As tags were never updated it was a security threat (public vuln un-patched).  If you want to upgrade, juste pull :latest and you're done.
