### ISSUE TITLE
Docker image for ARM architecture

### ISSUE THREAD

**Issue by Ivan-Igorevich** [Enalean/docker-tuleap-aio#67]
I was trying to run an image on a RaspberryPi but failed. Searched for the issue on the internet, and found out that RPi images somehow differ. Is there any plan to make Tuleap runnable on ARM devices?

**Comment by LeSuisse** [comment]
Hi,

ATM no there is no immediate plan. The support of ARM on CentOS/RHEL 7, is still a bit of a dev/advanced thing and builds are not quite up to date, notably for the packages coming from repositories like Remi where we get our PHP dependencies.
There is also a few packages in the Tuleap repository that would need to be built for the ARM architecture to be able to use all the features.

The ARM architecture is becoming quite common so ultimately we might get there but it's very unlikely that happen before the upcoming RHEL/CentOS 8 release where ARM64 is one of the announced supported target.
