### ISSUE TITLE
Cannot start service (tuleap-aio empty)

### ISSUE THREAD

**Issue by aiac** [Enalean/docker-tuleap-aio#68]
I can't run fresh install. After cloning repository and `docker-compose up` i got:
`ERROR: for tuleap  Cannot start service tuleap: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/share/tuleap/tools/docker/tuleap-aio/run.sh\": stat /usr/share/tuleap/tools/docker/tuleap-aio/run.sh: no such file or directory": unknown`

Running bash from this container show that `/usr/share/tuleap/` is empty. Tried to exec /usr/share/tuleap-install/setup.sh, but got the same error.

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
