### ISSUE TITLE
Issues running Tuleap with docker-compose.

### ISSUE THREAD

**Issue by wmrsp** [Enalean/docker-tuleap-aio#69]
1. Set a mysql root password in environment:
   ```
   $> export MYSQL_ROOT_PASSWORD=$(cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 15 | head -1)
   tr: Illegal byte sequence
   ```
1. Data volume issue:
   ```
   $> git clone https://github.com/Enalean/docker-tuleap-aio tuleap-aio
   $> cd tuleap-aio
   $> sed -i -e 's/${MYSQL_ROOT_PASSWORD:-ChangeMe}/1234/g' docker-compose.yml
   $> docker-compose up -d
   $> docker-compose down
   $> docker-compose up
   ...
   [33mtuleap_1  |[0m 2019-01-24 13:20:38,815 INFO gave up: nginx entered FATAL state, too many start retries too quickly
   ```
   See [issue-2.log](https://github.com/Enalean/docker-tuleap-aio/files/2791845/issue-2.log)
1. Database issue:
   ```
   $> git clone https://github.com/Enalean/docker-tuleap-aio tuleap-aio
   $> cd tuleap-aio
   $> sed -i -e 's/${MYSQL_ROOT_PASSWORD:-ChangeMe}/1234/g' docker-compose.yml
   $> sed -i -e 's/-\ db-data/-\ ~\/Code\/docker\/compose\/tuleap\/db-data/g' docker-compose.yml
   $> docker-compose up -d
   $> docker-compose down
   $> docker-compose up
   ...
   [33mtuleap_1  |[0m ERROR 2003 (HY000): Can't connect to MySQL server on 'db' (111)
   ```
    See [issue-3.log](https://github.com/Enalean/docker-tuleap-aio/files/2791875/issue-3.log)
1. Try to connect Tuleap to an external database by using the following `environment` settings in the `docker-compose.yml`:
   ```
   environment:
      DB_HOST: docker.for.mac.localhost
      MYSQL_DATABASE: tuleap
      MYSQL_ROOT_PASSWORD: 1234
   ```
   Open Sequel Pro and try to access the user's window ,**CMD+U** or **Database > User Accounts...**, will first give an error <img width="592" alt="sequel-pro-error" src="https://user-images.githubusercontent.com/21021680/51681741-d69b8900-1fe5-11e9-88d7-0cae14b720b1.png">.
   Try to open the user accounts window again and it is visible that the *root* user is now gone and, even though being logged into the database as the root user, it is no longer possible to assign global privileges. 
<img width="1078" alt="sequel-pro-root-user" src="https://user-images.githubusercontent.com/21021680/51681883-4742a580-1fe6-11e9-84e3-218497d5db98.png">

All in all, it appears as though the Tuleap service can only be ran once while being connected to it's own database, or database container. When destroying the container and re-creating it, it will not connect properly to the persistent data volumes or pre-existing database without crashing. Also it does some strange things to the root user of the database.

These issues make this docker container good to give the Tuleap a try but it is not a solid foundation to use docker to host the Tuleap software in production. That is a shame because so far I really like the Tuleap software.

**Comment by vaceletm** [comment]
You are more than right `tuleap-aio` image is not meant for production at all, it's a purely demo/test environment, the docker-compose method was proposed as a demo but never really meant for a "real install". I guess we should rather drop it entirely.

**Comment by wmrsp** [comment]
In that case, please don't mind my ticket :). It does work perfectly fine for trying out the Tuleap service and gave me a quick way of setting everything up and give it a spin. Much obliged!

Personally I think this image serves its purpose quite well. You might consider making it more clear that the image is only meant as a demo.

I'll close the ticket due to *misinterpretation*.
