### ISSUE TITLE
Tuleap admin user

### ISSUE THREAD

**Issue by thelinuxer** [Enalean/docker-tuleap-aio#7]
Hi,

I have installed tuleap using docker. Can't seem to login using admin/siteadmin. Can I please know what's the default admin username and password ?

Thanks.

**Comment by vaceletm** [comment]
The password is displayed at first boot time, you should be able to retrieve it  with
`docker exec tuleap_container_name cat /root/.tuleap_passwd`

**Comment by thelinuxer** [comment]
No such file in /root

cat: /root/.tuleap_passwd: No such file or directory

**Comment by thelinuxer** [comment]
Checking /srv/docker/pink/root/.tuleap_passwd from the host revealed the passwords.

Thanks :)

**Comment by gigabyte7ipev** [comment]
Run docker and use: "docker exec -ti 92ee6120cd9f... cat /data/root/.tuleap_passwd"

> Mysql user (root) : xxxx
> Codendiadm unix & DB (codendiadm): yyyy
> Libnss-mysql DB user (dbauthuser): zzz
> Site admin password (admin): www
