### ISSUE TITLE
Cannot start image on Archlinux

### ISSUE THREAD

**Issue by 8sd** [Enalean/docker-tuleap-aio#70]
I tried to start the image on my arch machine. After executing the `docker run` command docker exits with the error code `139`.

Some research showed there is an issue with running `CentOS 6`-based image on arch.

https://unix.stackexchange.com/questions/478387/

**Comment by LeSuisse** [comment]
Hi,

Yes this is known issue, see #57.

**Comment by stratosgear** [comment]
Hi, I see both this and #57 are closed issues.  Does this mean you have given up on the issues arch users are having demoing this?

Is there an issue I can subscribe to follow up when this might be able to work on arch server without changing the boot sequence?

**Comment by LeSuisse** [comment]
We have not given up, work is ongoing to move the image to CentOS 7 which solve the issue. You can follow the progress here: https://tuleap.net/plugins/tracker/?aid=13394 and in the branch centos7 of this repository.

**Comment by stratosgear** [comment]
Thanks, that's exactly the information I was looking for.
