### ISSUE TITLE
Moving Tuleap to another server

### ISSUE THREAD

**Issue by feuerball11** [Enalean/docker-tuleap-aio#72]
Hi,

i had serveral times the Problem, that i cant restore tuleap on another server, based on the Files inside a mounted directory. 

I copied the Data in my volume over to another server, set the settings to the same as the previous server, and deployed a new Docker container, linking to the old data. 

But direct after Start of the container, the image is frozen in a loop of:

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Wait for the db`

The error log from mysql only states:
 `190523 11:25:24 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
/usr/libexec/mysqld: File './tuleap-bin.index' not found (Errcode: 13)
190523 11:25:24 [ERROR] Aborting

190523 11:25:24 [Note] /usr/libexec/mysqld: Shutdown complete
`

which i dont know why it says this, becouse it can write to the error file in the same directory. 

Last times i solved it with just starting a new tuleap, but this time i realy need to restore the old data. So what do i do?

**Comment by vaceletm** [comment]
That probably means that files are not at the right place. It's hard to tell more precisly without more context (esp the command you run on both servers)

**Comment by feuerball11** [comment]
Okey, so i have tuleap running inside a docker on Server A. And i want to move to Server B. 

i copied the files over with this command:

`rsync -av -e ssh user@serverA.local:/path/to/tuleap/ /volume1/docker/tuleap_data/`
(i replaced path and user for security reasons)

and startet a new docker container pointing at the copied data. 

then i had the above error.
i noticed that in my old docker location, all files had the same user and group, but if i make a new container without old data, some have diffrent user / groups (like mysql with 496 or something like that) 

so i used this script to copy over permisions from an new tuleap, to my old data:

`D1=/volume1/docker/tuleap_data_working; D2=/volume1/docker/tuleap_data; for entry in $(find $D1  -exec stat -c "%u:%g&%N" {} \;); do $( echo $entry | sed 's#'$D1'#'$D2'#' | sed 's#&# #' | sed 's#‘##' | sed 's#’##' | { read line; echo 'chown -R '$line; } ) ; done`

which results in error 500.

i also changed the server adress in local.inc 

i tried a few diffrent things already, with diffrent results. once i had it running, but could not open projects... didnt manage to get this far a second time though...

i invested over 10 houres in this problem already. it shouldnt be so difficult to move from one server to another, if i already have it all inside docker...

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
