### ISSUE TITLE
Docker Compose issue on RHEL 7.5

### ISSUE THREAD

**Issue by fagnerffcs** [Enalean/docker-tuleap-aio#73]
I tried to run Tuleap using Docker Compose but no luck so far.

It just hangs in this line:

`/home/codendiadm/.ssh/id_rsa_gl-adm already exists.`

And after that:

`docker-tuleap-aio_tuleap_1 exited with code 1`

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
