### ISSUE TITLE
Project trackers are not copied when creating project from template in docker environment

### ISSUE THREAD

**Issue by kirkytullins** [Enalean/docker-tuleap-aio#76]
Hi support 
I haved created a docker instance of tuleap to test locally based on installation instructions found [here](https://hub.docker.com/r/enalean/tuleap-aio/) 

I was able to run the container and connect as admin on the new instance. 

The issue is : 

When I try to create a new project based on an existing project or template project, I get a code 500 when I click on submit. 

Result : The project is created but all the trackers are missing from the created project 

Do you have an idea why this might be happening ? 

Note: I'm using latest image version (enalean/tuleap-aio) from docker hub

Thanks

**Comment by vaceletm** [comment]
Please share some [logs](https://docs.tuleap.org/administration-guide/system-administration/logs.html) (at least error nginx) + exact version of tuleap you are running (cat /usr/share/tuleap/VERSION)

**Comment by kirkytullins** [comment]
Version is 11.3.99.32
How do I get the logs ?

**Comment by kirkytullins** [comment]
One thing I forgot to mention is that I'm running tuleap inside docker for windows. Is there any recommendation against it ?

**Comment by vaceletm** [comment]
The logs are on the container, you can copy them with docker cp
I don't know what is the impact of running on windows

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
