### ISSUE TITLE
Zend-mail doesn't work while sending email

### ISSUE THREAD

**Issue by ehfazrezwan** [Enalean/docker-tuleap-aio#77]
I setup Tuleap using the docker image running on Ubuntu 18.04.2 LTS. I managed to get it running, except it seems that the mail plugin isn't working. Specifically, the Zend-mail functionality. Here is the output of my nginx error log:
`2019/08/03 07:38:11 [error] 1417#0: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Zend\Mail\Exception\InvalidArgumentException: '104.248.158.24'$ Stack trace: #0 /usr/share/tuleap/src/vendor/zendframework/zend-mail/src/AddressList.php(233): Zend\Mail\Address->__construct('noreply@104.248...', 'Tuleap') #1 /usr/share/tuleap/src/vendor/zendframework/zend-mail/src/AddressList.php(33): Zend\Mail\AddressList->createAddress('noreply@104.248...', 'Tuleap') #2 /usr/share/tuleap/src/vendor/zendframework/zend-mail/src/Message.php(535): Zend\Mail\AddressList->add('noreply@104.248...', 'Tuleap') #3 /usr/share/tuleap/src/vendor/zendframework/zend-mail/src/Message.php(130): Zend\Mail\Message->updateAddressList(Object(Zend\Mail\AddressList), 'noreply@104.248...',$ #4 /usr/share/tuleap/src/vendor/zendframework/zend-mail/src/Message.php(117): Zend\Mail\Message->addFrom('noreply@104.248...', 'Tuleap') #5 /" while reading response header from upstream, client: 113.11.40.46, server: 104.248.158.24, request: "POST /admin/register_admin.php?page=admin_creation HTTP/1.1"$`

This is the output of /var/log/nginx/error.log

**Comment by rolandoisidoro** [comment]
@ehfazrezwan, it looks as you're using `noreply@104.248.158.24` as the the `from` or the `to` address, which I think might be the reason you're getting the exception from `Zend Mail`. Have you tried with a more conventional address with a domain instead of an IP after the `@` char, something like "email@address.com"?

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
