### ISSUE TITLE
Tuleap 11.0

### ISSUE THREAD

**Issue by JosiahDub** [Enalean/docker-tuleap-aio#79]
Hello. Would it be possible to release a docker container for Tuleap 11.0 or newer?

**Comment by LeSuisse** [comment]
Hi,

The image enalean/tuleap-aio@latest on the Docker Hub is updated every day with the latest changes so it is currently using Tuleap 11.5.X.

**Comment by JosiahDub** [comment]
Thank you, that is good to know. My company is using the 10.0 image. I am not sure how they choose which image so I will ask them to clarify.

**Comment by LeSuisse** [comment]
Since no news has been given, I'm closing this one.
