### ISSUE TITLE
VIRTUAL_HOST isn't used on title page

### ISSUE THREAD

**Issue by shaded-enmity** [Enalean/docker-tuleap-aio#8]
Hey,

I set the `VIRTUAL_HOST` env var to my hostname:

```
docker run -ti -e VIRTUAL_HOST=my.host -p 80:80 -p 443:443 -p 2222:22 -v /srv/docker/pink:/data enalean/tuleap-aio
```

The title page loads fine, but all links still lead to localhost:

```
https://localhost/account/register.php
https://localhost/account/login.php
```

**Comment by shaded-enmity** [comment]
Note that this might be a race condition somewhere, re-running the container a few times made this go away - will try to replicate the problem.

**Comment by vaceletm** [comment]
What is the content of $sys_default_domain and $sys_https_host in
/etc/tuleap/conf/local.inc ?

On Fri, Feb 26, 2016 at 9:20 AM, Causa Sui <notifications@github.com> wrote:

> Note that this might be a race condition somewhere, re-running the
> container a few times made this go away - will try to replicate the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Enalean/docker-tuleap-aio/issues/8#issuecomment-189158131>
> .
>



-- 
Manuel VACELET
Enalean Co-founder & Chief Technical Officer
+33 (0)7 61 10 89 90
Skype: manuel.vacelet.enalean
http://www.enalean.com
Twitter @vaceletm <https://twitter.com/vaceletm>

**Comment by shaded-enmity** [comment]
Both `my.host` in this testing instance.

Note that it was only the page body that had these `localhost` links, the top-bar was fine.

**Comment by vaceletm** [comment]
All links on front page are relative, so if you load http://my.host, links should be based on that

**Comment by vaceletm** [comment]
With latest version of the image, do you still have the same issue ?

**Comment by LeSuisse** [comment]
Not able to reproduce with the latest image. Feel free to reopen if needed.
