### ISSUE TITLE
Tuleap utility CLI does not work

### ISSUE THREAD

**Issue by RimShao** [Enalean/docker-tuleap-aio#80]
Hi Tuleap,

I don't have SUSE Linux environment and I would like to run Tuleap utility CLI inside docker tuleap container to publish files to tuleap server we already have.

then I face the below php error, Is Tuleap utility CLI supported by docker tuleap-aio image?

#docker exec -it 26cc2490d55a bash
[root@26cc2490d55a /]# php /usr/share/tuleap/src/utils/tuleap.php
PHP Parse error:  syntax error, unexpected T_FUNCTION, expecting T_PAAMAYIM_NEKUDOTAYIM in /usr/share/tuleap/src/utils/tuleap.php on line 43

Thanks and looking forward to your reply.

**Comment by LeSuisse** [comment]
Hi,

Just call `tuleap` or `/usr/bin/tuleap`. The Tuleap CLI will be called with the correct version of PHP.

**Comment by RimShao** [comment]
Hi LeSuisse,

Thanks a lot for the quick response.

Good to know about that, basically we are migrating the tuleap from SUSE Linux to docker container on Ubuntu, so we need migrate below SUSE tuleap command to run on docker container correspondingly.

#tuleap.php login --username=admin --password=admin
#tuleap.php myprojects
#tuleap.php frs getPackages --project=$openalm_eyang_project 
#tuleap.php frs getReleases --package_id=$package_id --project=$openalm_eyang_project 
#tuleap.php frs addRelease --package_id=$package_id --name=$release_name --notes="Maturity: Pre-GA." --project=$openalm_eyang_project		
#tuleap.php frs addFile --package_id=$package_id --release_id=$new_release_id --project=$openalm_eyang_project --comment="Maturity: Pre-GA." --local_file=$target_module_archive

Let me use run "#tuleap.php login/frs" as example, then I have new errror, do you have any idea about that ? Thanks

[root@26cc2490d55a /]# /usr/bin/tuleap login
  Command "login" is not defined.
[root@26cc2490d55a /]# 
[root@26cc2490d55a /]# /usr/bin/tuleap frs addRelease
  Command "frs" is not defined.

**Comment by vaceletm** [comment]
Humm, it seems you are refering to legacy tuleap **client** CLI (soap based) that was located in /usr/share/tuleap/cli

This was removed from tuleap in 2017 and of course is no longer supported.

If you need to automate stuff, you should use the REST API

**Comment by RimShao** [comment]
Hi Vaceletm,

Thanks for the information.

Actually we already tried REST API way before start client CLI, the reason we could not continue with REST API is because of we were stuck in tus upload problem, there is one bug https://tuleap.net/plugins/tracker/?aid=13492&group_id=101 

There is a bug reported in the open source project, It is supposed to be fixed but our server end do not have that version installed (fixed in Tuleap 11.4) and they do not plan to upgrade till some time in October. 


So do you have the old docker image which support tuleap client CLI(soap based) , we might could use that temporarily before REST API solution when our server end upgrade the bug fixed version.

BR//
Rim

**Comment by LeSuisse** [comment]
No we do not have that since we do not support it ;) .

Indeed, the issue described in [request #13492](https://tuleap.net/plugins/tracker/?aid=13492) has been fixed in Tuleap 11.4 so the only adequate solution is to update your instance. We cannot encourage people to run outdated versions.
