### ISSUE TITLE
I can not change the organization logo

### ISSUE THREAD

**Issue by brunogabrielli** [Enalean/docker-tuleap-aio#82]
I've followed the instructions of the oficial documentation (https://docs.tuleap.org/administration-guide/system-administration/customisations.html) and put the image files in the folder /etc/tuleap/themes/common/images but nothing changes.

The content of the folder is this:

```
[root@0492119f42dc images]# pwd
/etc/tuleap/themes/common/images
[root@0492119f42dc images]# ll
total 16
-rw-rw-r-- 1 codendiadm codendiadm 1150 Nov  8 12:29 favicon.ico
-rw-r--r-- 1 codendiadm codendiadm 5587 Nov  8 11:34 organization_logo.png
-rw-r--r-- 1 codendiadm codendiadm  872 Nov  8 11:35 organization_logo_small.png
```

I'm running the version 11.7.99.124 of the Tuleap in a Docker container.

What am I doing wrong?

**Comment by rolandoisidoro** [comment]
@brunogabrielli , I started testing Tuleap using its docker container a few versions ago and set my organization logo without any problem, just by following the instructions you mentioned. Just now I was using version 11.7.99.101 and updated, when I noticed you were a little ahead, bringing me to version 11.8.99.13 and still the logos keep showing as expected.

Have you checked your browser's developer tools to see if there's any error occurring behind the scenes? The first things that comes to mind are file ownership and permissions. Here's a screenshot of my container's `/etc/tuleap/themes/common/images/` directory listing, which shows the owner as `codendiadm` and the permissions set to `0644`:

![image](https://user-images.githubusercontent.com/1101532/68956313-bbda1100-07bf-11ea-8f2e-789c931de4f5.png)

**Comment by brunogabrielli** [comment]
@rolandoisidoro how you can see in the image below, the permissions are correct now. But the problem persists.

![image](https://user-images.githubusercontent.com/6934603/69231869-cdd20000-0b81-11ea-8e6c-4f00eb426ba1.png)

I can't understand the reason.

**Comment by tcottier-enalean** [comment]
Hi, 

The doc is probably outdated, to change your logo, as site admin, go to Administratation -> Homepage and upload it.

**Comment by brunogabrielli** [comment]
@tcottier-enalean in Administration-> Homepage you change the logo of the Homepage. 

We are talking about the logo in the header of the Tuleap instance.

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
