### ISSUE TITLE
Don't boot

### ISSUE THREAD

**Issue by mzch** [Enalean/docker-tuleap-aio#83]
When doing `docker-compose up`, `db` is up without problem, but `tuleap` always aborted.
It said,
```
tuleap-aio_tuleap_1 exited with code 139
```

OS: Debian 10 (Buster)

**Comment by LeSuisse** [comment]
Hi,

This is a known issue due to the usage of CentOS6 for the base image. See #57.

There is now an image based on CentOS 7 enalean/tuleap-aio:centos7. It is not yet the default but it should work.
