### ISSUE TITLE
Why the 'latest' version of tuleap-aio is not updated for 2 months?

### ISSUE THREAD

**Issue by xzhub** [Enalean/docker-tuleap-aio#84]
Hi
I'd like to know why the 'latest' version is 2 months old but the 'centos7' version is always up to date.  Do you have plan to upgrade the 'latest' version? 

https://hub.docker.com/r/enalean/tuleap-aio/tags

Thanks

**Comment by vaceletm** [comment]
Nope we don't.
centos6 branch is deprecated and people should use centos7 base (more widely compatible).
