### ISSUE TITLE
Plugin Agiledashboard

### ISSUE THREAD

**Issue by verissimomanoel** [Enalean/docker-tuleap-aio#86]
When I install the Tuleap using docker and centos7 the agiledashboard does not work. Do they have any idea?

**Comment by vaceletm** [comment]
Could you be more specific ?

**Comment by verissimomanoel** [comment]
I found the problem. In Dockerfile doesn't have a tuleap-plugin-agiledashboard to install and after this using the Plugin Manager you need install the plugin. Please close the bug!
