### ISSUE TITLE
tuleap.local can not be opened

### ISSUE THREAD

**Issue by TQxTim** [Enalean/docker-tuleap-aio#90]
I've followed the "How to use it" instructions and cannot access the enelean/tuleap-aio:centos7 container via browser.
The Container is up and running and shows no log errors.
Directly accessing the ip with any combination of valid ports was not successful.
Manually mapping ports to the container was also not successful.

Is there something I am missing?

**Comment by LeSuisse** [comment]
Hello,

Can you please tell us what do you mean by "was not successful"? What does happen?

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
