### ISSUE TITLE
No templates in the "Start new project" view

### ISSUE THREAD

**Issue by pmaslankowski** [Enalean/docker-tuleap-aio#93]
Hi,

Today I pulled the docker image based on centos7. I ran it and although everything seems to work smoothly, when I try to create a new project, there are no templates available (as in the screenshot below):

![tuleap-new-project](https://user-images.githubusercontent.com/16786704/105986674-85737380-609d-11eb-88d5-c669cad70091.png)

I've been currently using an older version of the image (centos6, Tuleap 11.x) and I could choose an Agile project from available templates there. Did you remove these templates from new versions? If so, what is the easiest way to configure a new agile project?

I also tried to choose an empty project template, but I can't configure an agile board then - in the services tab of project settings there is no Agile Dashboard service.

Versions:
Tuleap version: Tuleap Community Edition — Dev Build 12.4.99.187
Image digest: sha256:0dd9529549899e07efcf9abaf57432e446094b574423dab05c39b4e75663fce9

Thanks for your help

**Comment by vaceletm** [comment]
You need to install plugins in the image to have more templates (agiledashboard, git & co)

**Comment by pmaslankowski** [comment]
Thanks! After installing plugins everything works. Sorry for the trouble :)

**Comment by LeSuisse** [comment]
@vaceletm What do you think about enabling a few plugins (Git, Tracker, Agile Dashboard ?) by default in the image to avoid this sort of issues?
