### ISSUE TITLE
New project creation is not working 

### ISSUE THREAD

**Issue by guthom** [Enalean/docker-tuleap-aio#96]
Hello all together,

i installed the test docker container and everything works as expected. 

But when i try to create a new project nothing is happening. 
A red error indicator  with none information at all apears on top of the page (attached imaga) - any ideas? 

It is a blank centos7 installataion with just running the container.

Thanks!

![image](https://user-images.githubusercontent.com/51358569/111474336-41f7c600-872c-11eb-9b66-5f9bf222aa42.png)

**Comment by vaceletm** [comment]
The avatar seems to indicate that you have a configuration mismatch between what's defined in `/etc/tuleap/conf/local.inc` as server name  (and what you have in your browser location bar.
Could you please check that ?

**Comment by guthom** [comment]
Thank you very much! It worked, yes i needed to change the tuleap.local in the config.
